### PR TITLE
fix: update walletlink connector

### PR DESCRIPTION
**Pull request by brendanww**
Updates @web3-react/walletlink-connector to 6.2.3. This will resolve bug where network sometimes does not sync correctly when updated from Coinbase Wallet mobile apps.

### CODE REVIEW

**Comment by brendanww** [comment]
@bmino is there anything I can do to help move this PR forward?

**Comment by bmino** [comment]
Hey! Can you give some more details about how this bug happens and symptoms?

**Comment by brendanww** [comment]
@bmino the version of web3-react currently on `master` uses version `2.0.2` of walletlink. That means folks who connect to pangolinswap using walletlink without the Coinbase Wallet extension will not be able to sync networks at all. We didn't add hooks to emit chain updates from mobile clients until `2.1.4` (https://github.com/walletlink/walletlink/pull/114). Since our extension injects the most recent version of walletlink into pangolinswap, this problem doesn't show up for users using the extension.

**Comment by bmino** [comment]
Gotcha, thanks!

**Pull request merged**
