### PR TITLE
solve issues on farm page

### PR DESCRIPTION
**Pull request by SarjuHansaliya**
- farm page: fix "No active rewards" showing while api is loading
- show `-` instead of undefined% in APR while we are fetching data

### CODE REVIEW

**Comment by bmino** [comment]
Cool! Gonna check this in particular against the version 0 (old staking) as I hit issues trying something similar last time where those pools never loaded

**Comment by bmino** [comment]
Can we remove the additional filter on isPeriodFinished inside the `stakingInfoData` handler? We've already filtered by this before creating `stakingInfoData`

**Comment by SarjuHansaliya** [comment]
@bmino its done. sorry somehow I missed it.

**Comment by bmino** [comment]
Thanks! Rebased and moved this to #142. All credit to ya good sir 😉

**Pull request closed without merging**
