### PR TITLE
Fix/hector.remove update token modal

### PR DESCRIPTION
**Pull request by fstar1129**
It removed the "Accept" modal when the token list are updated. So should not display any popup when the token list are updated and be automatically updated in the background.

### CODE REVIEW

**Comment by HariSeldon23** [comment]
Hey @fstar1129, can you please add more description to your PR's so that we know what they're for.

@SarjuHansaliya can you review and merge? This is a feature to remove accepting token lists when we update them. The user should just automatically have the new tokenlists. They shouldn't have to accept them

**Comment by fstar1129** [comment]
> Hey @fstar1129, can you please add more description to your PR's so that we know what they're for.
> 
> @SarjuHansaliya can you review and merge? This is a feature to remove accepting token lists when we update them. The user should just automatically have the new tokenlists. They shouldn't have to accept them

Edited the description above

**Comment by SarjuHansaliya** [comment]
sure @HariSeldon23, let me review

**Review by SarjuHansaliya — APPROVED** [review]

**Review by SarjuHansaliya — APPROVED** [review]
lgtm

**Comment by SarjuHansaliya** [comment]
@HariSeldon23 I have reviewed this PR. but looks like I don't have rights to merge.

**Pull request merged**
