### PR TITLE
fix: update walletlink-connector to 6.2.7

### PR DESCRIPTION
**Pull request by brendanww**
Update walletlink-connector to 6.2.7 which updates to a version of walletlink that supports EIP-3085 addEthereumChain/switchEthereumChain requests.

### CODE REVIEW

**Comment by bmino** [comment]
testing this out and it looks great so far!

**Comment by bmino** [comment]
Getting a persistent init screen after connecting:
image

This avoids the repeated infura queries that were happening before

**Comment by bmino** [comment]
This was via MM, but we can get a variety of wallets to test on the live `dev` branch

**Comment by bmino** [comment]
TrustWallet is still working great

**Comment by brendanww** [comment]
thank you @bmino !

**Pull request merged**
