### PR TITLE
Beta UI Responsive and better performance

### PR DESCRIPTION
**Pull request by light-co-turkey**
Beta UI Responsive and better performance Update
-Dashboard responsive, port, news, watchlist
-SwapPage responsive, mobile charts, rid of watchlist and port,
-PoolPage partner buttons enabled on mobile
-PopUpWarning no more pop up nav floating

( I have done moderate testing, and have not came across any compiling problems )

### CODE REVIEW

**Comment by light-co-turkey** [comment]
Highlights of this PR in my opinion are;
-use of css flex more often
-sidebar no collapse very important!
-smaller chart
-legacy, beta buttons for mobile
-keeping focus of the ui elements in the center of the app

notes:
-Portfolio widget could be added to swap page as well
-Dashboard page can be made more responsive between 400px and 1200px range ( ipads and bigger phones )
-Better practice of max width for 4k and 2k dispalys ( could be done by css vw or calc() )

**Comment by SarjuHansaliya** [comment]
1. I see that you have removed collapsible feature from sidebar. but we need that feature, we dont want sidebar to visible always
2. we have already fixed dashboard responsiveness, please sync your changes with dev branch
3. Swap page doesn't looks good at all in 13'' screen, please check this [screenshot](https://prnt.sc/kbXA-5-tfE66) . Doesn't match design which was done by Abdullah
4. scrollbar stopped working in sidebar. https://prnt.sc/hSw-XYCAPSBy
5. sidebar social media icons are not aligned properly
there are many more things which are not matching with our current design which was finalized by Abdullah

**Comment by light-co-turkey** [comment]
Alright I have made this pr to give a feel of what I mean I can come up with more compatible ui flexes as soon as I find time.

Although, collapse bar is extremely annoying to use, as a user myself and an artist, also technically that mouse on and off board function is bugging the display and lagging the screen, we should move away from this. We should focus on having human tangible designs!!

**Comment by SarjuHansaliya** [comment]
got it. if we want to discuss about design, we need to include Abdullah in the discussion as he is lead designer making decisions.

**Pull request closed without merging**
