### PR TITLE
Add a Buy option with Sendwyre

### PR DESCRIPTION
**Pull request by benber86**
Will allow users to purchase AVAX with fiat via a redirect to Sendwyre
We still need to wait for:

- Sendwyre support for Avalanche C-Chain (I ran tests with an ETH setup, which will need to be updated)
- Sendwyre API keys (Requires updating the .env file or environment variables before deployment)

### CODE REVIEW

**Comment by ASlowCheetah** [comment]
This is freaking awesome.

**Comment by HariSeldon23** [comment]
> This is freaking awesome.

Yup, it's pretty great! We're just waiting for C Chain support. So hoping this will go into testing in two weeks and then from there we can roll out soon after.

**Comment by HariSeldon23** [comment]
@benber86 @bmino should we consider having Code Coverage tests on these PR's in future? Something like SonarQube https://www.sonarqube.org/

**Review by HariSeldon23 — COMMENTED** [review]
Hey @benber86, Abdullah has been working on the UI for this integration.

You can find it here https://xd.adobe.com/view/0fc9b071-6053-4e37-a5a1-bb6fbd1e9ea2-5a9a/screen/08675ec1-16f9-496c-aed8-ccd0746c3922

Would it make sense to incorporate this for when we go live?

Robi will also be implementing a backend system that will deploy these PR's to a live site. Hopefully that will be live in the next few weeks

**Comment by HariSeldon23** [comment]
Hey @bmino, it would be good to add these environment variables to Github before pushing this live.

**Comment by bmino** [comment]
Upon entering a value into the USD field, the dapp crashes with errors looking for CryptoJS
image

**Comment by bmino** [comment]
I'm also missing the keys when testing locally so could also affect this?

**Review by bmino — APPROVED** [review]
looks good for dev! wanna make sure the keys are picked up correctly especially

**Pull request merged**
