### PR TITLE
Next release to incorporate working changes

### PR DESCRIPTION
**Pull request by HariSeldon23**
- Staking changes
- Mobile Stake UI
- Sentry improvements
- Assorted mobile fixes

### CODE REVIEW

**Comment by HariSeldon23** [comment]
Task linked: [CU-21uxfz0 Implement Mobile view of pool/farms list](https://app.clickup.com/t/21uxfz0)

**Comment by HariSeldon23** [comment]
Task linked: [CU-21uxfj5 Implement Mobile view of single side staking list](https://app.clickup.com/t/21uxfj5)

**Comment by HariSeldon23** [comment]
Task linked: [CU-21uxjr8 Implement mobile view of single side staking details page](https://app.clickup.com/t/21uxjr8)

**Comment by HariSeldon23** [comment]
Task linked: [CU-226db5b implement a strategy to increment build version number on every deployment so we can track bug in sentry for each deployment](https://app.clickup.com/t/226db5b)

**Comment by HariSeldon23** [comment]
Task linked: [CU-226h6ef Implement staking flow after claim so user can stake already claim rewards without leaving flow](https://app.clickup.com/t/226h6ef)

**Review by SarjuHansaliya — APPROVED** [review]

**Pull request merged**
