### PR TITLE
FIx sonarcloud issues part 2

### PR DESCRIPTION
**Pull request by prodesert22**
**Fixed code smell**

- ['../constants' import is duplicated.](https://sonarcloud.io/project/issues?issues=AYAWgdH2XGiBufZy_V--&open=AYAWgdH2XGiBufZy_V--&id=pangolindex_interface)
- ['last' is already declared in the upper scope.](https://sonarcloud.io/project/issues?issues=AYAWgdHwXGiBufZy_V-9&open=AYAWgdHwXGiBufZy_V-9&id=pangolindex_interface)
- [Immediately return this expression instead of assigning it to the temporary variable "isBeta"](https://sonarcloud.io/project/issues?issues=AYAWgdISXGiBufZy_V_N&open=AYAWgdISXGiBufZy_V_N&id=pangolindex_interface)
- [Default parameters should be last.](https://sonarcloud.io/project/issues?issues=AYAWgdIGXGiBufZy_V_C&open=AYAWgdIGXGiBufZy_V_C&id=pangolindex_interface)
- [Default parameters should be last.](https://sonarcloud.io/project/issues?issues=AYAWgdIGXGiBufZy_V_E&open=AYAWgdIGXGiBufZy_V_E&id=pangolindex_interface)
- ['state' is already declared in the upper scope.](https://sonarcloud.io/project/issues?issues=AYAWgdHpXGiBufZy_V-7&open=AYAWgdHpXGiBufZy_V-7&id=pangolindex_interface)
- [Consider removing 'undefined' type or '?' specifier, one of them is redundant.](https://sonarcloud.io/project/issues?issues=AYAWgdHAXGiBufZy_V-0&open=AYAWgdHAXGiBufZy_V-0&id=pangolindex_interface)
- [Unnecessary semicolon.](https://sonarcloud.io/project/issues?issues=AYAWgdLmXGiBufZy_V_5&open=AYAWgdLmXGiBufZy_V_5&id=pangolindex_interface)
- [Remove this commented out code.](https://sonarcloud.io/project/issues?issues=AYAWgdKxXGiBufZy_V_s&open=AYAWgdKxXGiBufZy_V_s&id=pangolindex_interface)
- [Update this function so that its implementation is not identical to the one on line 180.](https://sonarcloud.io/project/issues?issues=AYAWgdLDXGiBufZy_V_y&open=AYAWgdLDXGiBufZy_V_y&id=pangolindex_interface)
- [Remove this commented out code.](https://sonarcloud.io/project/issues?issues=AYAWgdKnXGiBufZy_V_r&open=AYAWgdKnXGiBufZy_V_r&id=pangolindex_interface)
- ['error' is already declared in the upper scope.](https://sonarcloud.io/project/issues?issues=AYAWgc8jXGiBufZy_V6l&open=AYAWgc8jXGiBufZy_V6l&id=pangolindex_interface)
- ['currencyA' is already declared in the upper scope.](https://sonarcloud.io/project/issues?issues=AYAWgc8jXGiBufZy_V6m&open=AYAWgc8jXGiBufZy_V6m&id=pangolindex_interface)
- ['currencyB' is already declared in the upper scope.](https://sonarcloud.io/project/issues?issues=AYAWgc8jXGiBufZy_V6n&open=AYAWgc8jXGiBufZy_V6n&id=pangolindex_interface)
- [Extract this nested ternary operation into an independent statement.](https://sonarcloud.io/project/issues?issues=AYAWgdGHXGiBufZy_V-f&open=AYAWgdGHXGiBufZy_V-f&id=pangolindex_interface) and others in same file
- [Remove this commented out code.](https://sonarcloud.io/project/issues?issues=AYAWgdF0XGiBufZy_V-S&open=AYAWgdF0XGiBufZy_V-S&id=pangolindex_interface)
- ['src/constants' import is duplicated.](https://sonarcloud.io/project/issues?issues=AYAWgdAaXGiBufZy_V7u&open=AYAWgdAaXGiBufZy_V7u&id=pangolindex_interface)
- [Remove this commented out code.](https://sonarcloud.io/project/issues?issues=AYAWgdAaXGiBufZy_V7z&open=AYAWgdAaXGiBufZy_V7z&id=pangolindex_interface)
- ['src/constants' import is duplicated.](https://sonarcloud.io/project/issues?issues=AYAWgdEGXGiBufZy_V9Q&open=AYAWgdEGXGiBufZy_V9Q&id=pangolindex_interface)
- ['i' is already declared in the upper scope.](https://sonarcloud.io/project/issues?issues=AYAWgdEGXGiBufZy_V9U&open=AYAWgdEGXGiBufZy_V9U&id=pangolindex_interface)
- [Remove this commented out code.](https://sonarcloud.io/project/issues?issues=AYAWgdBmXGiBufZy_V8L&open=AYAWgdBmXGiBufZy_V8L&id=pangolindex_interface) and other in same file
- ['src/hooks' import is duplicated](https://sonarcloud.io/project/issues?issues=AYAWgdBmXGiBufZy_V8M&open=AYAWgdBmXGiBufZy_V8M&id=pangolindex_interface)
- [Update this function so that its implementation is not identical to the one on line 33.](https://sonarcloud.io/project/issues?issues=AYAWgdBrXGiBufZy_V8P&open=AYAWgdBrXGiBufZy_V8P&id=pangolindex_interface)
- ['src/hooks' import is duplicated.](https://sonarcloud.io/project/issues?issues=AYAWgdC1XGiBufZy_V8j&open=AYAWgdC1XGiBufZy_V8j&id=pangolindex_interface)
- ['error' is already declared in the upper scope.](https://sonarcloud.io/project/issues?issues=AYAWgdC1XGiBufZy_V8n&open=AYAWgdC1XGiBufZy_V8n&id=pangolindex_interface)
- [This assertion is unnecessary since it does not change the type of the expression.](https://sonarcloud.io/project/issues?issues=AYAWgdC1XGiBufZy_V8o&open=AYAWgdC1XGiBufZy_V8o&id=pangolindex_interface) and other in same file
- [Remove this commented out code.](https://sonarcloud.io/project/issues?issues=AYAWgdC1XGiBufZy_V8q&open=AYAWgdC1XGiBufZy_V8q&id=pangolindex_interface)
- ['src/hooks' import is duplicated.](https://sonarcloud.io/project/issues?issues=AYAWgdC9XGiBufZy_V8r&open=AYAWgdC9XGiBufZy_V8r&id=pangolindex_interface)
- ['src/state/stake/hooks' import is duplicated.](https://sonarcloud.io/project/issues?issues=AYAWgdDHXGiBufZy_V8s&open=AYAWgdDHXGiBufZy_V8s&id=pangolindex_interface)
- ['src/utils/wrappedCurrency' import is duplicated.](https://sonarcloud.io/project/issues?issues=AYAWgdDHXGiBufZy_V8t&open=AYAWgdDHXGiBufZy_V8t&id=pangolindex_interface)
- ['error' is already declared in the upper scope.](https://sonarcloud.io/project/issues?issues=AYAWgdDHXGiBufZy_V8x&open=AYAWgdDHXGiBufZy_V8x&id=pangolindex_interface) and others in same file
- ['typedValue' is already declared in the upper scope.](https://sonarcloud.io/project/issues?issues=AYAWgdDHXGiBufZy_V81&open=AYAWgdDHXGiBufZy_V81&id=pangolindex_interface)
- ['pair' is already declared in the upper scope.](https://sonarcloud.io/project/issues?issues=AYAWgdDHXGiBufZy_V83&open=AYAWgdDHXGiBufZy_V83&id=pangolindex_interface)
- [This assertion is unnecessary since it does not change the type of the expression.](https://sonarcloud.io/project/issues?issues=AYAWgdDHXGiBufZy_V84&open=AYAWgdDHXGiBufZy_V84&id=pangolindex_interface)
- [Extract this nested ternary operation into an independent statement.](https://sonarcloud.io/project/issues?issues=AYAWgdCDXGiBufZy_V8T&open=AYAWgdCDXGiBufZy_V8T&id=pangolindex_interface) and orthers in same file
- ['src/hooks' import is duplicated.](https://sonarcloud.io/project/issues?issues=AYAWgdCIXGiBufZy_V8X&open=AYAWgdCIXGiBufZy_V8X&id=pangolindex_interface)
- ['src/state/burn/hooks' import is duplicated.](https://sonarcloud.io/project/issues?issues=AYAWgdDXXGiBufZy_V87&open=AYAWgdDXXGiBufZy_V87&id=pangolindex_interface)
- ['error' is already declared in the upper scope.](https://sonarcloud.io/project/issues?issues=AYAWgdDXXGiBufZy_V8-&open=AYAWgdDXXGiBufZy_V8-&id=pangolindex_interface)
- ['typedValue' is already declared in the upper scope.](https://sonarcloud.io/project/issues?issues=AYAWgdDXXGiBufZy_V8_&open=AYAWgdDXXGiBufZy_V8_&id=pangolindex_interface)
- [Complete the task associated to this "TODO" comment.](https://sonarcloud.io/project/issues?issues=AYAWgdDXXGiBufZy_V9B&open=AYAWgdDXXGiBufZy_V9B&id=pangolindex_interface)
- [This assertion is unnecessary since it does not change the type of the expression.](https://sonarcloud.io/project/issues?issues=AYAWgdDXXGiBufZy_V9I&open=AYAWgdDXXGiBufZy_V9I&id=pangolindex_interface)
- ['@pangolindex/components' import is duplicated.](https://sonarcloud.io/project/issues?issues=AYAWgdB1XGiBufZy_V8Q&open=AYAWgdB1XGiBufZy_V8Q&id=pangolindex_interface)
- ['src/hooks' import is duplicated.](https://sonarcloud.io/project/issues?issues=AYAWgdCQXGiBufZy_V8Y&open=AYAWgdCQXGiBufZy_V8Y&id=pangolindex_interface)
- [Update this function so that its implementation is not identical to the one on line 32.](https://sonarcloud.io/project/issues?issues=AYAWgdCWXGiBufZy_V8a&open=AYAWgdCWXGiBufZy_V8a&id=pangolindex_interface)
- ['src/state/stake/hooks' import is duplicated.](https://sonarcloud.io/project/issues?issues=AYAWgdBWXGiBufZy_V8A&open=AYAWgdBWXGiBufZy_V8A&id=pangolindex_interface)
- ['error' is already declared in the upper scope.](https://sonarcloud.io/project/issues?issues=AYAWgdBWXGiBufZy_V8C&open=AYAWgdBWXGiBufZy_V8C&id=pangolindex_interface)
- ['./Sidebar' import is duplicated.](https://sonarcloud.io/project/issues?issues=AYAWgdBMXGiBufZy_V79&open=AYAWgdBMXGiBufZy_V79&id=pangolindex_interface)
- ['error' is already declared in the upper scope.](https://sonarcloud.io/project/issues?issues=AYAWgc9OXGiBufZy_V6_&open=AYAWgc9OXGiBufZy_V6_&id=pangolindex_interface)
- ['src/theme' import is duplicated.](https://sonarcloud.io/project/issues?issues=AYAWgc-CXGiBufZy_V7L&open=AYAWgc-CXGiBufZy_V7L&id=pangolindex_interface)
- ['src/constants' import is duplicated.](https://sonarcloud.io/project/issues?issues=AYAWgc9wXGiBufZy_V7D&open=AYAWgc9wXGiBufZy_V7D&id=pangolindex_interface)
- [This assertion is unnecessary since it does not change the type of the expression.](https://sonarcloud.io/project/issues?issues=AYAWgc9wXGiBufZy_V7F&open=AYAWgc9wXGiBufZy_V7F&id=pangolindex_interface)
- ['error' is already declared in the upper scope.](https://sonarcloud.io/project/issues?issues=AYAWgc9hXGiBufZy_V7B&open=AYAWgc9hXGiBufZy_V7B&id=pangolindex_interface)
- [Remove this commented out code.](https://sonarcloud.io/project/issues?issues=AYAWgc9hXGiBufZy_V7C&open=AYAWgc9hXGiBufZy_V7C&id=pangolindex_interface)
- ['src/constants' import is duplicated.](https://sonarcloud.io/project/issues?issues=AYAWgc-LXGiBufZy_V7M&open=AYAWgc-LXGiBufZy_V7M&id=pangolindex_interface)
- [This assertion is unnecessary since it does not change the type of the expression.](https://sonarcloud.io/project/issues?issues=AYAWgc-LXGiBufZy_V7N&open=AYAWgc-LXGiBufZy_V7N&id=pangolindex_interface)
- ['error' is already declared in the upper scope.](https://sonarcloud.io/project/issues?issues=AYAWgc-kXGiBufZy_V7S&open=AYAWgc-kXGiBufZy_V7S&id=pangolindex_interface)
- [Remove this commented out code.](https://sonarcloud.io/project/issues?issues=AYAWgc-5XGiBufZy_V7V&open=AYAWgc-5XGiBufZy_V7V&id=pangolindex_interface)

### CODE REVIEW

**Comment by HariSeldon23** [comment]
Task linked: [CU-2fdh260 Fix sonarcloud issues](https://app.clickup.com/t/2fdh260)

**Comment by HariSeldon23** [comment]
@prodesert22 you'll need to reduce the duplicate code before this can get merged

**Comment by prodesert22** [comment]
> @prodesert22 you'll need to reduce the duplicate code before this can get merged

Some of this duplicated is false positives

**Comment by HariSeldon23** [comment]
Ok cool. I'll override it and merge then

**Pull request merged**
