### PR TITLE
 Add Remove Button in Watchlist

### PR DESCRIPTION
**Pull request by prodesert22**
- Added Remove Button in watchlist widget
- Replaced old coins widget for watchlist widget in dashboard
- Removed percentage in portfolio widget on dashboard
- Added "Switch to new UI" button on old UI
- Added link in side bar to Axelar's Satellite Bridge

### CODE REVIEW

**Comment by HariSeldon23** [comment]
Not sure if this intentional, but you can't remove PNG from the Watchlist.

I love it!

**Comment by prodesert22** [comment]
> Not sure if this intentional, but you can't remove PNG from the Watchlist.
> 
> I love it! However we then shouldn't display the "X" when hovering over PNG
> 
> Also not sure why some tokens are duplicating? What tokenlist are we using? image

1. It is not possible to remove the PNG because when the list is empty it shows the PNG, when you click on remove it removes the PNG but the list is empty again which ends up showing the PNG 
2. I'll think of a way to do this
3. I believe I should get all the tokenlists, I believe @SarjuHansaliya can confirm this information

**Comment by SarjuHansaliya** [comment]
currently we are listing tokens from `src/constants/coinLists.ts`, but yes we can use tokenlists to list coins

**Comment by HariSeldon23** [comment]
Gonna merge so that we can open it up for testing to a wider audience. I know there may be a few issues, but considering launch date is so close I think it's prudent to get this into users hands so we can get real user feedback

**Pull request merged**
